### ISSUE TITLE
SFK Door

### ISSUE THREAD

**Issue by Yacopok** [LightsHope/issues#397]
Hello there.
Just a quick and easy bug to fix.
The door in Shadowfang Keep which is located right after Fenrus the Devourer should open upon his defeat. It does not work as intended at the moment and it never opens.

**Comment by ratkosrb** [comment]
This issue is not reproducible on development branch, but i am working on re-implementing the script. That will probably end up fixing whatever the issue is on live servers.

**Comment by ratkosrb** [comment]
Should be fixed after https://github.com/lh-server/core/commit/700d272741b1f80b005368e3f9ccff15da470405

**Comment by Musashii89** [comment]
Can confirm this is NOT fixed yet.

**Comment by ratkosrb** [comment]
Are you testing on development branch or LH live servers? This fix is not on live servers yet.

**Comment by sh728** [comment]
I just walked through SFK in LH live server, the bug still exists

**Comment by ratkosrb** [comment]
Test on development branch, not LH live servers. This fix is not applied there yet.

**Comment by sh728** [comment]
When it can be applied to LH live servers?

**Comment by ghost** [comment]
How can we test on the QA Dev server, are we able to as standard players?

**Comment by ratkosrb** [comment]
Follow the guide to build the latest development branch here https://github.com/ratkosrb/server/wiki/Compiling-on-Windows

Or use the latest repack which is from August 9th. It is available on AC-Web and Ownedcore, just google for "Light's Hope Repack".
