### ISSUE TITLE
Mobs spamming AoE aura doing insane dmg

### ISSUE THREAD

**Issue by latyy** [LightsHope/issues#810]
Sometimes it seems like mobs who have an aura that does aoe dmg bugs out sometimes and they SPAM the aoe like crazy.

We've lost buffs now twice because of this and its very annoying to spend hours/days rolling DMF and sniping buffs to have this happen within first 10min of a raid.

Video proof here : https://clips.twitch.tv/SpineyVainWalletPeanutButterJellyTime
It happened a few weeks ago also.

**Comment by Cabro** [comment]
I also noticed it happening on the golems in EPL.

**Comment by Road-block** [comment]
This used to happen 100% with [Lord Alexei Barov](http://classicdb.ch/?npc=10504)'s aura few months ago.  
Where we purposely did a pull / reset (with rogue or hunter etc) as it only happened on first pull.  
Aura worked properly 2nd pull onwards.  
It was fixed since so whatever was done there could probably be replicated for these mobs.  
Anyone has tried a pull/reset to see if it's only on first combat init?

**Comment by bladezLH** [comment]
Happens  randomly

**Comment by fitigf15** [comment]
still happening btw... https://www.twitch.tv/cadet_15/clip/BetterAggressiveWrenchOhMyDog?filter=clips&range=all&sort=time nice world buffs I had right there 😢
